Repository Mi-Ss-A/portfoliosvc, pull requests merged in 2024-11, with the labels that each got.

#3 feat:Spring Boot 초기 세팅(#2)
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/wibeechat/missa/MissaApplication.java
  src/main/java/com/wibeechat/missa/config/test.txt
  src/main/java/com/wibeechat/missa/controller/test.txt
  src/main/java/com/wibeechat/missa/dto/test.txt
  src/main/java/com/wibeechat/missa/entity/test.txt
  src/main/java/com/wibeechat/missa/repository/test.txt
  src/main/java/com/wibeechat/missa/service/test.txt
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/MissaApplicationTests.java
Labels: feat

#11 feat: portpolio controller 기본 골조 생성 (#7)
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/controller/test.txt
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioDetailResponse.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioRequest.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioResponse.java
  src/main/java/com/wibeechat/missa/dto/test.txt
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
  src/main/java/com/wibeechat/missa/service/test.txt
Labels: feat, refactor

#14 refactor: redis config 설정
  src/main/java/com/wibeechat/missa/config/RedisConfig.java
  src/main/resources/application.properties
Labels: refactor

#15 feat: 카드 데이터 한정 포트폴리오 생성 완료
  build.gradle
  src/main/java/com/wibeechat/missa/config/RestTemplateConfig.java
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/dto/portfolio/AssetDistributionData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/CardTransactionData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/FundTransactionTypeData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/LoanStatusData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/LoanTransactionData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/MonthlyBankInOutData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioDetailResponse.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioResponse.java
  src/main/java/com/wibeechat/missa/dto/portfolio/RepaymentSummaryData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/TransactionTimelineData.java
  src/main/java/com/wibeechat/missa/service/portfolio/ChartService.java
  src/main/java/com/wibeechat/missa/service/portfolio/ExtractTransactionService.java
  src/main/java/com/wibeechat/missa/service/portfolio/HtmlService.java
  src/main/java/com/wibeechat/missa/service/portfolio/KibanaService.java
  src/main/java/com/wibeechat/missa/service/portfolio/PdfService.java
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
  src/main/resources/templates/portfolio.html
Labels: feat, help

#16 feat: s3 upload 기능 구현
  build.gradle
  src/main/java/com/wibeechat/missa/config/SwaggerConfig.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioResponse.java
  src/main/java/com/wibeechat/missa/service/portfolio/ChartService.java
  src/main/java/com/wibeechat/missa/service/portfolio/ExtractTransactionService.java
  src/main/java/com/wibeechat/missa/service/portfolio/KibanaService.java
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
  src/main/java/com/wibeechat/missa/service/portfolio/S3Service.java
Labels: feat

#17 feat: 포트폴리오 리스트 기능
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioResponse.java
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
  src/main/java/com/wibeechat/missa/service/portfolio/S3Service.java
Labels: feat

#18 feat login 기능 추가
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioRequest.java
Labels: feat, refactor

#21 chore: unused file del and refactor code (#20)
  src/main/java/com/wibeechat/missa/component/CurrentUserArgumentResolver.java
  src/main/java/com/wibeechat/missa/component/SessionManager.java
  src/main/java/com/wibeechat/missa/config/SessionConfig.java
  src/main/java/com/wibeechat/missa/config/SwaggerConfig.java
  src/main/java/com/wibeechat/missa/config/WebMvcConfig.java
  src/main/java/com/wibeechat/missa/config/test.txt
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/dto/portfolio/FundTransactionTypeData.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioRequest.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioResponse.java
  src/main/java/com/wibeechat/missa/dto/portfolio/TransactionTimelineData.java
  src/main/java/com/wibeechat/missa/entity/test.txt
  src/main/java/com/wibeechat/missa/interceptor/LoginCheckInterceptor.java
  src/main/java/com/wibeechat/missa/repository/test.txt
  src/main/java/com/wibeechat/missa/service/portfolio/ChartService.java
  src/main/java/com/wibeechat/missa/service/portfolio/ExtractTransactionService.java
  src/main/java/com/wibeechat/missa/service/portfolio/HtmlService.java
  src/main/java/com/wibeechat/missa/service/portfolio/KibanaService.java
  src/main/java/com/wibeechat/missa/service/portfolio/PdfService.java
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
  src/main/java/com/wibeechat/missa/service/portfolio/S3Service.java
Labels: refactor

#27 refactor: redis session id 기반 수정 (#26)
  src/main/java/com/wibeechat/missa/config/RedisSessionListener.java
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
  src/main/java/com/wibeechat/missa/dto/portfolio/PortfolioRequest.java
  src/main/java/com/wibeechat/missa/service/portfolio/PortfolioService.java
Labels: feat, refactor

#29 refactor: mapping fix (#28)
  src/main/java/com/wibeechat/missa/controller/portfolio/PortfolioController.java
Labels: refactor
